#!/bin/bash

docker kill $(docker ps -q);
docker system prune
docker build -t companion_ai:latest --build-arg value=$(pwd) .
docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/companionAI/mnt -u ${UID} -d -p 8080:8080 --rm companion_ai