basePath: /api/v1
info:
  contact: {}
paths:
  /model/predict/{modelId}/{modelVersion}:
    post:
      consumes:
      - application/json
      description: generates prediction for the datapoint
      parameters:
      - description: unique id for models
        in: path
        name: modelId
        required: true
        type: string
      - description: use version v1 if no other versions exist
        in: path
        name: modelVersion
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
swagger: "2.0"
