basePath: /api/v1
definitions:
  dockerManager.ContainerInformation:
    properties:
      ip:
        type: string
      modelId:
        type: string
      port:
        type: string
      version:
        type: string
    type: object
  helper.EntityDataPoint:
    properties:
      entities:
        items:
          $ref: '#/definitions/helper.EntityInformation'
        type: array
      id:
        type: string
      sentence:
        type: string
    type: object
  helper.EntityDataPoints:
    properties:
      dataPoints:
        items:
          $ref: '#/definitions/helper.EntityDataPoint'
        type: array
    type: object
  helper.EntityInformation:
    properties:
      end:
        type: integer
      start:
        type: integer
      type:
        type: string
    type: object
  helper.IdBody:
    properties:
      ids:
        items:
          type: string
        type: array
    type: object
  helper.LabelBody:
    properties:
      labels:
        items:
          type: string
        type: array
    type: object
  helper.ModelInformation:
    properties:
      labels:
        items:
          type: string
        type: array
      model-type:
        type: string
      newest-version:
        type: string
    type: object
  helper.ModelNames:
    properties:
      modelNames:
        items:
          type: string
        type: array
    type: object
  helper.ModelType:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  helper.ModelTypes:
    properties:
      modelTypes:
        items:
          $ref: '#/definitions/helper.ModelType'
        type: array
    type: object
  helper.NewModel:
    properties:
      name:
        type: string
      type:
        type: string
    type: object
info:
  contact: {}
paths:
  /data/entity_extraction/{modelId}:
    delete:
      consumes:
      - application/json
      description: removes multiple data points from the trainings-data
      parameters:
      - description: unique id for models
        in: path
        name: modelId
        required: true
        type: string
      - description: datapoints which should be removed
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/helper.IdBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - data
    get:
      consumes:
      - application/json
      description: gets all trainings-data
      parameters:
      - description: unique id for models
        in: path
        name: modelId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.EntityDataPoints'
      tags:
      - data
    post:
      consumes:
      - application/json
      description: adds multiple data points to the trainings-data
      parameters:
      - description: unique id for models
        in: path
        name: modelId
        required: true
        type: string
      - description: id can be ignored
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/helper.EntityDataPoints'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - data
  /model/{containerId}/stop:
    put:
      consumes:
      - application/json
      description: stops a single container with given id
      parameters:
      - description: unique id for a container
        in: path
        name: containerId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - model
  /model/{modelId}:
    delete:
      consumes:
      - application/json
      description: deletes a model and the trainings-data from the local file system
      parameters:
      - description: unique id for models
        in: path
        name: modelId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - model
    get:
      consumes:
      - application/json
      description: gets all necessary information for a model id
      parameters:
      - description: unique id for models
        in: path
        name: modelId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.ModelInformation'
      tags:
      - model
  /model/{modelId}/labels:
    delete:
      consumes:
      - application/json
      description: deletes labels from the config file
      parameters:
      - description: unique id for models
        in: path
        name: modelId
        required: true
        type: string
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/helper.LabelBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - model
  /model/create:
    post:
      consumes:
      - application/json
      description: creates a new folder with the necessary template files
      parameters:
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/helper.NewModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - model
  /model/predict/{modelId}/{modelVersion}:
    post:
      consumes:
      - application/json
      description: generates prediction for the datapoint
      parameters:
      - description: unique id for models
        in: path
        name: modelId
        required: true
        type: string
      - description: use version v1 if no other versions exist
        in: path
        name: modelVersion
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - model
  /models:
    get:
      consumes:
      - application/json
      description: creates a new folder with the necessary template files
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.ModelNames'
      tags:
      - models
  /models/runningContainers:
    get:
      consumes:
      - application/json
      description: stops all running containers which were started in this run
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dockerManager.ContainerInformation'
      tags:
      - models
  /models/stopAll:
    put:
      consumes:
      - application/json
      description: stops all running containers which were started in this run
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - models
  /models/types:
    get:
      consumes:
      - application/json
      description: returns all available types for creating a new model
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.ModelTypes'
      tags:
      - models
swagger: "2.0"
